## Поверхностное копирование

### Копирование списков

In [ ]:
from copy import copy

L = [1, 3, 5]

L_1 = L[:]      # первый способ
L_2 = list(L)   # второй способ
L_3 = copy(L)   # третий способ

> Подобным же образом можно скопировать также кортежи и строки. Однако, так как это итак неизменяемые типы данных, смысла в этом не много. Нобходимость скорее будет возникать в глубоком копировании.

### Копирование множеств и словарей

In [ ]:
from copy import copy

D = {"a": 3, "b":3}
D_2 = dict(D)
D_3 = copy(D)

S = {0, 1, 2, 3, 4}
S_2 = set(S)
S_3 = copy(S)

## Глубокое копирование

In [ ]:
from copy import deepcopy

L_4 = deepcopy(L)
D_4 = deepcopy(D)
S_4 = deepcopy(S)

## Срезы

In [ ]:
s = 'Text'

a, b, c, d = s[:2], s[2:], s[:-2], s[-2:]
print(a, b, c, d)

a, b, = s[:-1], s[-1]
print(a, b)

(a, b), c = s[:2], s[2:]
print(a, b, c)

Te xt Te xt
Tex t
T e xt


Более общий синтаксис:

    L[start: end: step]


In [ ]:
L = list(range(12))
print(f'{  L         = }')
print(f'{  L[3:10:2] = }')  # каждый второй элемент в диапазоне от 3 до 10
print(f'{  L[5::4]   = }')  # каждый четвертый элемент начиная с 5
print(f'{  L[1::2]   = }')  # все элементы с нечетными индексами
print(f'{  L[::2]    = }')  # все элементы с четными индексами [0::2]
print(f'{  L[::3]    = }')  # каждый третий элемент начиная с нулевого

  L        = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
  L[1::2]  = [1, 3, 5, 7, 9, 11]
  L[::2]   = [0, 2, 4, 6, 8, 10]
  L[::3]   = [0, 3, 6, 9]
  L[5::4]  = [5, 9]


In [ ]:
# срезы в обратном порядке:
print(f'{ L       = }')
print(f'{ L[10:3:-2] = }') # каждый второй элемент в диапазоне от 10 до 3
print(f'{ L[3::-1] = }')   # первые 4 элемента в обратном порядке
print(f'{ L[::-1] = }')    # все элементы в обратном порядке
print(f'{ L[::-3] = }')    # каждый третий эл. с конца начиная с последнего

 L       = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
 L[::-1] = [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
 L[::-3] = [11, 8, 5, 2]
 L[3::-1] = [3, 2, 1, 0]
 L[10:3:-2] = [10, 8, 6, 4]


> Пусть матрица `A` задана в виде списка списков. Получить копию строки можно примерно так же, как и для матрицы NumPy: `A[1][:]`, но вот с копией колонки такой номер не пройдет: `A[:][1]` также возрващает копию строки с индексом `1`:

In [ ]:
A = [
    [ 1,  2,  3,  4],
    [ 5,  6,  7,  8],
    [ 9, 10, 11, 12],
    [13, 14, 15, 16]
]
print(f"{  A[1][:]   = }")      # копия строки с индексом 1
print(f"{  A[:][1]   = }")      # копия строки с индексом 1

  A[1][:]   = [5, 6, 7, 8]
  A[:][1]   = [5, 6, 7, 8]


### Срезы в NumPy

In [ ]:
import numpy as np

A = np.array(A)
print(f"{  A[1, :]   = }")      # строка с индексом 1
print(f"{  A[:, 1]   = }")      # колонка с индексом 1
print(f"{  A[1, 2:]  = }")      # строка с индексом 1
print(f"{  A[:2, 1]  = }")      # колонка с индексом 1
print(f"{  A[::2, 1] = }")      # колонка с индексом 1

  A[1, :]   = array([5, 6, 7, 8])
  A[:, 1]   = array([ 2,  6, 10, 14])
  A[1, 2:]  = array([7, 8])
  A[:2, 1]  = array([2, 6])
  A[::2, 1] = array([ 2, 10])


## Фильтрация массива по маске

### Создание маски

Для массива `b` выражение `b%2==0` возвращает булевый массив, содержащий `True` в тех позициях, где элемент массива `b` является четным, и `False` – где элемент массива `b` является четным.

In [ ]:
import numpy as np

a = np.arange(8)
b = np.random.randint(0, 100, 8)

b_odd = b%2==0

print(f'{a = }')
print(f'{b = }')
print(f'{b_odd = }')
print(f'{b_odd.dtype = }')

a = array([0, 1, 2, 3, 4, 5, 6, 7])
b = array([84, 32, 43, 86, 70, 23, 62, 22])
b_odd = array([ True,  True, False,  True,  True, False,  True,  True])
b_odd.dtype = dtype('bool')


### Наложение маски
В данном случае массив `b_odd` той же формы что и массив `a`, можно использовать в качестве фильтрующего массива для `a`, если передать его в квадратные скобки:

In [ ]:
a_filtered = a[b_odd]
print(f'{a_filtered = }')

a_filtered = array([0, 1, 3, 4, 6, 7])


In [ ]:
# можно было бы сразу записать так:
a_filtered = a[b%2==0]
print(f'{a_filtered = }')

a_filtered = array([0, 1, 3, 4, 6, 7])


### Получение строк и колонок матрицы по маске

In [ ]:
import numpy as np

X = np.random.randint(0, 10, (6, 6))    # двумерный маcсив
mask = X[:, 0] > 5                      # маска по колонке с индексом 0
print(f"{ X }\n\n{ mask }")
X[X[:, 0] > 5]                          # получение строк по маске

[[4 1 2 1 9 4]
 [2 4 0 6 8 7]
 [0 9 9 0 7 1]
 [0 7 5 2 9 4]
 [8 7 3 6 4 5]
 [6 8 4 3 6 6]]

[False False False False  True  True]


array([[8, 7, 3, 6, 4, 5],
       [6, 8, 4, 3, 6, 6]])

In [ ]:
obj = np.array([2, 4, 6, 8, 5, 3])
X[:, (5 > obj)]                         # получение колонок по маске

array([[4, 1, 4],
       [2, 4, 7],
       [0, 9, 1],
       [0, 7, 4],
       [8, 7, 5],
       [6, 8, 6]])

## Fancy Indexing

В NumPy вы можете использовать список индексов в квадратных скобках для выбора элементов из массива.

In [ ]:
import numpy as np

tags = np.array([0.0, 1.1, 2.2, 3.3, 4.4, 5.5])
tags[[1, 4, 3, 4, -1]]

array([1.1, 4.4, 3.3, 4.4, 5.5])

Для многомерных массивов:

In [ ]:
X = np.random.randint(0, 10, (3, 3))    # двумерный маcсив
print(X)
X[[0, 1], [2, 2]]

[[5 8 6]
 [6 5 0]
 [8 8 2]]


array([6, 0])

## Распаковка, операторы `*` и `**`

### Распаковка последовательностей
Синтаксис **распоковок** (*unpacking*) одинаков для всех любых итерируемых объектов: `list`, `str`, `tuple`, `ndarray` и тд.

Распаковка при **параллельном присваивании** (*parallel assignment*), т.е. присваивание элементов итерируемого объекта кортежу переменных:

In [ ]:
a, b, c, d = 'text'         # распаковка
print(a, b, c, d)

t e x t


Распаковка кортежей в цикле, которые являются элементами списка. Кортежи сами содержат вложенные кортежи, но если выражение соответствует структуре вложенности, Python правильно заполнит переменные:

In [ ]:
L = [(-i, -j, (i, j)) for i in range(2) for j in range(2)]
print(L)

for k, p, (i, j) in L:
    print(k, p, i, j)

[(0, 0, (0, 0)), (0, -1, (0, 1)), (-1, 0, (1, 0)), (-1, -1, (1, 1))]
0 0 0 0
0 -1 0 1
-1 0 1 0
-1 -1 1 1


Распаковка последовательности при передаче в качестве аргумента при вызове функции:

In [ ]:
t = [20, 8]
a, b = divmod(*t)
a, b

(2, 4)

## Распаковка словарей

Избыток аргументов функции может быть запакован в `**kwargs`. Но также можно распаковать словарь при передаче его в функцию в качестве аргумента, используя оператор `**`.

In [ ]:
def f(a, b, c):
    print(a * b * c)

d = {"c": 3, "b": 2}

f(4, **d)

24


In [ ]:
def f(**kwargs):
    for key, value in kwargs.items():
        print(key, value)

d = {"c": 3, "b": 2}
f(**d)

c 3
b 2


> Распаковка словаря при помощи оператора `*` приведет к тому, что распаконы будут только ключи

In [ ]:
d = {"c": 3, "b": 2}
print(*d)

c b


## Упаковка

При параллельном присваивании число переменных должно соответствовать длине последовательности. Однако аналогично тому, как в функциях избыток аргументов запаковывается в `*args`, при параллельном присваивании также есть возможность извлечь из последовательности некоторые элементы в переменные, а остальное запаковать в список. Для этого используется оператор `*` перед одной из переменных, которой и будет присвоен этот список. Перменная с `*` может занимать любую позицию:

In [ ]:
*a, b = 'text'
print(a, b)

a, *b, c = 'text'
print(a, b, c)

a, b, c, d, *e = 'text'
print(a, b, c, d, e)

['t', 'e', 'x'] t
t ['e', 'x'] t
t e x t []
