<a href="https://colab.research.google.com/github/ordevoir/Misc_Private/blob/main/python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Разное

## Not a Number (`NaN`)

Один из способов создания объекта Not a Number – передать в конструктор класса `float` строковые значения `'nan'` или `'NaN'`:

In [2]:
NaN = float('nan')  # Not a Number
print(f'{   NaN        = }')
print(f'{   type(NaN)  = }')

   NaN        = nan
   type(NaN)  = <class 'float'>
   bool(NaN)  = True


In [16]:
float('NaN') is float('NaN')

False

Некоторые свойства объекта `nan`:

In [40]:
print(f'{   bool(NaN)  = }')
print(f'{   NaN == NaN = }')


   bool(NaN)  = True
   NaN == NaN = False


In [22]:
print(f"{ NaN + 10 = }")
print(f"{ NaN - 10 = }")
print(f"{ NaN * 10 = }")
print(f"{ NaN / 10 = }")

 NaN + 10 = nan
 NaN - 10 = nan
 NaN * 10 = nan
 NaN / 10 = nan


Объект Not a Number можно взять из библиотеки NumPy. Для этого определены константы `nan` и `NaN`, которые ссылаются на один и тот же объект:

In [37]:
import numpy as np
np.nan is np.NaN

True

Объект Not a Number можно взять из модуля `math`:

In [38]:
import math
math.nan

float

Для того, чтобы проверить является ли объект Not a Number, можно воспользоваться функцией `isnan()` из библиотеки NumPy или из модуля `math`:

In [42]:
np.isnan(NaN), math.isnan(NaN)

(True, True)

Такая проверка позволит отфильтровать последовательность от значений Not a Number.

## Infinity

## Falsy and Truthy

Falsy значениями являются такие значения, которые при преобразовании в булевый тип дают `False`. Значения, которые при преобразовании дают `True` называются Truthy значениями.

В условных выражениях операторов `for`, `while`, `if`, `elif` значения Falsy интерпретируются как `False`, а значения Truthy – как `True`.

Числовыми Falsy значениями являются **нули**, остальные числовые значения являются Truthy.

Пустые коллекции являются Falsy, а непустые - Truthy.

Объект `None` является Falsy значением.

In [ ]:
# числа:
print(f'{  bool(0)          = }')
print(f'{  bool(0.)         = }')
print(f'{  bool(0j)         = }')
print(f'{  bool(0 + 0j)     = }\n')
# коллекции:
print(f'{  bool("")         = }')       # пустой string
print(f'{  bool([])         = }')       # пустой list
print(f'{  bool(())         = }')       # пустой tuple
print(f'{  bool({})         = }')       # пустой set
print(f'{  bool(dict())     = }')       # пустой dictionary
print(f'{  bool(range(0))   = }\n')     # пустой range
# тип None:
print(f'{  bool(None)       = }')
print(f'{  not None         = }\n')
# Not a number не является Falsy!
NaN = float('nan')
print(f'{  bool(NaN)        = }')

  bool(0)          = False
  bool(0.)         = False
  bool(0j)         = False
  bool(0 + 0j)     = False

  bool("")         = False
  bool([])         = False
  bool(())         = False
  bool({})         = False
  bool(dict())     = False
  bool(range(0))   = False

  bool(None)       = False
  not None         = True

  bool(NaN)        = True


## Сравнение c `bool`

Оператор `is` с операндом `False` возвращает `True`, в том, и только том случае, если второй операнд также является `False` (а не просто Falsy). Подобным образом оператор `is` работает и с операндом `True`. Это связано с тем, что оператор `is` проверяет, ссылаются ли операнды на один и тот же объект.

Оператор `==` с операндом `False` возвращает `True` только если второй операнд является *числовым* Falsy объектом (т.е. **нулевым**) или же непосредственно объектом `False`.

Оператор `==` с операндом `True` возвращает `True` только если второй операнд является *числовым* Truthy с **единичным** значением или же непосредственно объектом `True`.

При сравнении остальных стандартных типов с `False` или `True` оператор `==` будет всегда возвращать `False` (так как для них `==` означает `is`).

>При сравнении непосредственно булевых значений принято использовать оператор `is` вместо оператора `==`.

In [ ]:
# оператор == с нулями:
print(f'{  0 == False        = }')
print(f'{  0. == False       = }')
print(f'{  0j == False       = }')
print(f'{  0 + 0j == False   = }')
print(f'{  0 + 1j == False   = }\n')

# оператор == с единицами:
print(f'{  1 == True         = }')
print(f'{  1. == True        = }')
print(f'{  1 + 0j == True    = }')
print(f'{  0 + 1j == True    = }\n')

# коллекции:
print(f'{  "" == False       = }')       # пустой string
print(f'{  "a" == True       = }\n')       # пустой string

# None:
print(f'{  None == False     = }')
print(f'{  None is False     = }')

# здесь оператор not явно преобразовывает None в тип bool:
print(f'{  not None is True  = }\n')

  0 == False        = True
  0. == False       = True
  0j == False       = True
  0 + 0j == False   = True
  0 + 1j == False   = False

  1 == True         = True
  1. == True        = True
  1 + 0j == True    = True
  0 + 1j == True    = False

  "" == False       = False
  "a" == True       = False

  None == False     = False
  None is False     = False
  not None is True  = True



In [ ]:
print(f'{   False <= True  = }')
print(f'{   False < True   = }')
print(f'{   False > True   = }')
print(f'{   False >= True  = }')

   False <= True  = True
   False < True   = True
   False > True   = False
   False >= True  = False


## Стравнение c `None`

Выражение `x is None`  выдает всегда `True`, если `x` имеет значение `None`, и `False`, в любом другом случае.

Выражение  `x is not None`  выдает всегда `False`, если `x` имеет значение `None`, и `True`, в любом другом случае.

In [ ]:
value = 3

print(f'{  None is None         = }')
print(f'{  None == None         = }')

print(f'{  value is None        = }')
print(f'{  False is None        = }')
print(f'{  True is None         = }\n')

print(f'{  None is not None     = }')
print(f'{  None != None         = }')
print(f'{  value is not None    = }')
print(f'{  False is not None    = }')
print(f'{  True is not None     = }\n')

  None is None         = True
  None == None         = True
  value is None        = False
  False is None        = False
  True is None         = False

  None is not None     = False
  None != None         = False
  value is not None    = True
  False is not None    = True
  True is not None     = True



`is not` – это отдельный оператор, а не последовательность операторов `not` и `is`, поэтому `x is not None` не то же самое что и `x is (not None)`

При сравнении оператором `==` с типом `None` фактически задействуется оператор `is`, поэтому лучше всегда явно использовать `is` вместо `==`

In [ ]:
print(f'{  False is not None    = }')
print(f'{  False is (not None)  = }')
print(f'{  False == (not None)  = }')
print(f'{  True  == (not None)  = }\n')

  False is not None    = True
  False is (not None)  = False
  False == (not None)  = False
  True  == (not None)  = True



В одиночку, оператор `not` конвертирует `None` в булевый тип:

In [ ]:
print(f'{  not None       = }')
print(f'{  type(not None) = }')

  not None       = True
  type(not None) = <class 'bool'>


## Оператор инверсии `~`

Оператор `~` производит битовую инверсию челых чисел в two's-complement (дополнительный код) представлении. Например, число `10` в дополнительном коде представляется как `00001010`, инверсии этого числа `11110101` будет соответствовать число `-11`. Заметим, что исверсией нуля (`00000000`) будет -`1` (`11111111`).

In [ ]:
print(f"{ ~10    = }")
print(f"{ ~0     = }")
print(f"{ ~False = }")      # заметим, что для булевых значений выполняется
print(f"{ ~True  = }")      # конвертация в int, а не инверсия T в F

 ~10    = -11
 ~0     = -1
 ~False = -1
 ~True  = -2


Благодаря такому свойству оператор `~` может оказаться полезен при движении по массиву с конца, так как в отличие от использования отрицательных индексов, здесь сохраняется симметрия с движением по массиву с начала.

In [ ]:
A = [1, 2, 3, 4, 5]
print('i  A[i]  A[-i]  A[~i]')
for i in range(len(A)):
    print(f'{i}    {A[i]}      {A[-i]}      {A[~i]}')

i  A[i]  A[-i]  A[~i]
0    1      1      5
1    2      5      4
2    3      4      3
3    4      3      2
4    5      2      1


Своя специфика имеется при использовании оператора `~` с NumPy:
- Для булевых типов NumPy (`numpy.bool_`) производтся инверсия (в отличие от стандартных типов `bool`). А если оператор применить к массиву (или матрице), состоящему из логических элементов, то результатом будет массив, содержащий инверированные элементы.
- Если применить оператор к массиву (или матрице), состоящей из целочисленных элементов, то вернется матрица, состоящий из инвертрованных целых чисел (в соответствии с представлением в дополнительном коде).

In [ ]:
import numpy as np

print(f"{~np.False_ = }")   # для типов
print(f"{~np.True_  = }")    # numpy.bool_

L = np.array([False, True, False])

print(f"{~L = }")

A = np.array([0, 1, -2, 3])
print(f"{~A = }")

~np.False_ = True
~np.True_  = False
~L = array([ True, False,  True])
~A = array([-1, -2,  1, -4])


Для того, чтобы определить действие объекта пользовательсокго класса при воздействии оператора `~`, необходимо определить метод `__invert__()`.

In [ ]:
class C():
    def __invert__(self):
        print('! inverse by ~ !')
x = C()
~x

! inverse by ~ !


## Оператор Ellipsis (`...`)

In [ ]:
# to be defined
def f():
    ...
# Такая запись предполагает, что тело функции в дельнейшем должно быть
# определено (в отличие от pass, где намеренно пропускаются действия)

In [ ]:
import numpy as np

n = np.random.rand(3, 3, 3, 3)          # shape (3, 3, 3, 3)
print(n[..., 2])                        # <=> n[:, :, :, 2]

[[[0.96184506 0.94883132 0.29107255]
  [0.0860742  0.92776083 0.08257939]
  [0.72103826 0.49672237 0.00717213]]

 [[0.76313745 0.99897734 0.61497782]
  [0.79084103 0.49008086 0.62009155]
  [0.97780974 0.77977778 0.42719729]]

 [[0.38995664 0.18811921 0.15066886]
  [0.82393036 0.63199316 0.22398636]
  [0.09558114 0.33285623 0.56451095]]]
