<a href="https://colab.research.google.com/github/ordevoir/Misc_Private/blob/main/python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### `__call__`

In [ ]:
class Rectangle:
    def __init__(self) -> None:
        print('init')
        self.x = 10

    def __call__(self, y):
        print('call', self.x * y)

r = Rectangle()
r(2)

`__add__()` переопределяет поведение оператора +, однако, этот метод работает тогда, когда объект находится слева от оператора `__radd__()`позволяет определить поведение оператора + для случая, когда объект находится справа от + (right-sid-add)

In [ ]:
class Book(object):
    def __init__(self, author, title):  # инициализатор
        self.author = author
        self.title = title

    def __del__(self):                  # финализатор
        print(self, 'is deleted')

    def __repr__(self):
        return f'author: {self.author} \ntitle: {self.title}'

book = Book('Hermann Hesse', title='Das Glasperlenspiel')
print(book)

`__repr__` орпделеяет строковое представление класса (representation), т.е. как он будтет выводиться в `print`, и как его будет конвертировать функция `str()`. Метод `__del__` отвечает за финализацию: он вызывается перед удалением объекта.

In [ ]:

book.pageCount = 255

# hasattr() позволяет узнать, есть ли атрибут у объекта
# getattr() позволяет получить значение атрибута объекта
attr = 'pageCount'
if hasattr(book, attr):
    print(attr, getattr(book, attr))

# Разное

## Тернарный оператор (*Conditional Expression*)

In [ ]:
s = 'this' if 10 > 12 else 'not this'   # Conditional Expression

# равносильно условной инструкции:
if 10 > 12:                             # Conditional Statement
    s = 'this'
else:
    s = 'not this'
print(s)

not this


## Not a Number (`NaN`)

In [ ]:
NaN = float('nan')  # Not a Number
print(f'{   NaN        = }')
print(f'{   type(NaN)  = }')
print(f'{   bool(NaN)  = }')
# np.nan - так же представляет собой NaN

   NaN        = nan
   type(NaN)  = <class 'float'>
   bool(NaN)  = True


## Falsy and Truthy

Falsy значениями являются такие значения, которые при преобразовании в булевый тип дают `False`. Значения, которые при преобразовании дают `True` называются Truthy значениями.

В условных выражениях операторов `for`, `while`, `if`, `elif` значения Falsy интерпретируются как `False`, а значения Truthy – как `True`.

Числовыми Falsy значениями являются **нули**, остальные числовые значения являются Truthy.

Пустые коллекции являются Falsy, а непустые - Truthy.

Объект `None` является Falsy значением.

In [ ]:
# числа:
print(f'{  bool(0)          = }')
print(f'{  bool(0.)         = }')
print(f'{  bool(0j)         = }')
print(f'{  bool(0 + 0j)     = }\n')
# коллекции:
print(f'{  bool("")         = }')       # пустой string
print(f'{  bool([])         = }')       # пустой list
print(f'{  bool(())         = }')       # пустой tuple
print(f'{  bool({})         = }')       # пустой set
print(f'{  bool(dict())     = }')       # пустой dictionary
print(f'{  bool(range(0))   = }\n')     # пустой range
# тип None:
print(f'{  bool(None)       = }')
print(f'{  not None         = }\n')
# Not a number не является Falsy!
NaN = float('nan')
print(f'{  bool(NaN)        = }')

  bool(0)          = False
  bool(0.)         = False
  bool(0j)         = False
  bool(0 + 0j)     = False

  bool("")         = False
  bool([])         = False
  bool(())         = False
  bool({})         = False
  bool(dict())     = False
  bool(range(0))   = False

  bool(None)       = False
  not None         = True

  bool(NaN)        = True


## Сравнение c `bool`

Оператор `is` с операндом `False` возвращает `True`, в том, и только том случае, если второй операнд также является `False` (а не просто Falsy). Подобным образом оператор `is` работает и с операндом `True`. Это связано с тем, что оператор `is` проверяет, ссылаются ли операнды на один и тот же объект.

Оператор `==` с операндом `False` возвращает `True` только если второй операнд является *числовым* Falsy объектом (т.е. **нулевым**) или же непосредственно объектом `False`.

Оператор `==` с операндом `True` возвращает `True` только если второй операнд является *числовым* Truthy с **единичным** значением или же непосредственно объектом `True`.

При сравнении остальных стандартных типов с `False` или `True` оператор `==` будет всегда возвращать `False` (так как для них `==` означает `is`).

>При сравнении непосредственно булевых значений принято использовать оператор `is` вместо оператора `==`.

In [ ]:
# оператор == с нулями:
print(f'{  0 == False        = }')
print(f'{  0. == False       = }')
print(f'{  0j == False       = }')
print(f'{  0 + 0j == False   = }')
print(f'{  0 + 1j == False   = }\n')

# оператор == с единицами:
print(f'{  1 == True         = }')
print(f'{  1. == True        = }')
print(f'{  1 + 0j == True    = }')
print(f'{  0 + 1j == True    = }\n')

# коллекции:
print(f'{  "" == False       = }')       # пустой string
print(f'{  "a" == True       = }\n')       # пустой string

# None:
print(f'{  None == False     = }')
print(f'{  None is False     = }')

# здесь оператор not явно преобразовывает None в тип bool:
print(f'{  not None is True  = }\n')

  0 == False        = True
  0. == False       = True
  0j == False       = True
  0 + 0j == False   = True
  0 + 1j == False   = False

  1 == True         = True
  1. == True        = True
  1 + 0j == True    = True
  0 + 1j == True    = False

  "" == False       = False
  "a" == True       = False

  None == False     = False
  None is False     = False
  not None is True  = True



In [ ]:
print(f'{   False <= True  = }')
print(f'{   False < True   = }')
print(f'{   False > True   = }')
print(f'{   False >= True  = }')

   False <= True  = True
   False < True   = True
   False > True   = False
   False >= True  = False


## Стравнение c `None`

Выражение `x is None`  выдает всегда `True`, если `x` имеет значение `None`, и `False`, в любом другом случае.

Выражение  `x is not None`  выдает всегда `False`, если `x` имеет значение `None`, и `True`, в любом другом случае.

In [ ]:
value = 3

print(f'{  None is None         = }')
print(f'{  None == None         = }')

print(f'{  value is None        = }')
print(f'{  False is None        = }')
print(f'{  True is None         = }\n')

print(f'{  None is not None     = }')
print(f'{  None != None         = }')
print(f'{  value is not None    = }')
print(f'{  False is not None    = }')
print(f'{  True is not None     = }\n')

  None is None         = True
  None == None         = True
  value is None        = False
  False is None        = False
  True is None         = False

  None is not None     = False
  None != None         = False
  value is not None    = True
  False is not None    = True
  True is not None     = True



`is not` – это отдельный оператор, а не последовательность операторов `not` и `is`, поэтому `x is not None` не то же самое что и `x is (not None)`

При сравнении оператором `==` с типом `None` фактически задействуется оператор `is`, поэтому лучше всегда явно использовать `is` вместо `==`

In [ ]:
print(f'{  False is not None    = }')
print(f'{  False is (not None)  = }')
print(f'{  False == (not None)  = }')
print(f'{  True  == (not None)  = }\n')

  False is not None    = True
  False is (not None)  = False
  False == (not None)  = False
  True  == (not None)  = True



В одиночку, оператор `not` конвертирует `None` в булевый тип:

In [ ]:
print(f'{  not None       = }')
print(f'{  type(not None) = }')

  not None       = True
  type(not None) = <class 'bool'>


## Оператор инверсии `~`

Оператор `~` производит битовую инверсию челых чисел в two's-complement (дополнительный код) представлении. Например, число `10` в дополнительном коде представляется как `00001010`, инверсии этого числа `11110101` будет соответствовать число `-11`. Заметим, что исверсией нуля (`00000000`) будет -`1` (`11111111`).

In [ ]:
print(f"{ ~10    = }")
print(f"{ ~0     = }")
print(f"{ ~False = }")      # заметим, что для булевых значений выполняется
print(f"{ ~True  = }")      # конвертация в int, а не инверсия T в F

 ~10    = -11
 ~0     = -1
 ~False = -1
 ~True  = -2


Благодаря такому свойству оператор `~` может оказаться полезен при движении по массиву с конца, так как в отличие от использования отрицательных индексов, здесь сохраняется симметрия с движением по массиву с начала.

In [ ]:
A = [1, 2, 3, 4, 5]
print('i  A[i]  A[-i]  A[~i]')
for i in range(len(A)):
    print(f'{i}    {A[i]}      {A[-i]}      {A[~i]}')

i  A[i]  A[-i]  A[~i]
0    1      1      5
1    2      5      4
2    3      4      3
3    4      3      2
4    5      2      1


Своя специфика имеется при использовании оператора `~` с NumPy:
- Для булевых типов NumPy (`numpy.bool_`) производтся инверсия (в отличие от стандартных типов `bool`). А если оператор применить к массиву (или матрице), состоящему из логических элементов, то результатом будет массив, содержащий инверированные элементы.
- Если применить оператор к массиву (или матрице), состоящей из целочисленных элементов, то вернется матрица, состоящий из инвертрованных целых чисел (в соответствии с представлением в дополнительном коде).

In [ ]:
import numpy as np

print(f"{~np.False_ = }")   # для типов
print(f"{~np.True_  = }")    # numpy.bool_

L = np.array([False, True, False])

print(f"{~L = }")

A = np.array([0, 1, -2, 3])
print(f"{~A = }")

~np.False_ = True
~np.True_  = False
~L = array([ True, False,  True])
~A = array([-1, -2,  1, -4])


Для того, чтобы определить действие объекта пользовательсокго класса при воздействии оператора `~`, необходимо определить метод `__invert__()`.

In [ ]:
class C():
    def __invert__(self):
        print('! inverse by ~ !')
x = C()
~x

! inverse by ~ !


## Оператор Ellipsis (`...`)

In [ ]:
# to be defined
def f():
    ...
# Такая запись предполагает, что тело функции в дельнейшем должно быть
# определено (в отличие от pass, где намеренно пропускаются действия)

In [ ]:
import numpy as np

n = np.random.rand(3, 3, 3, 3)          # shape (3, 3, 3, 3)
print(n[..., 2])                        # <=> n[:, :, :, 2]

[[[0.96184506 0.94883132 0.29107255]
  [0.0860742  0.92776083 0.08257939]
  [0.72103826 0.49672237 0.00717213]]

 [[0.76313745 0.99897734 0.61497782]
  [0.79084103 0.49008086 0.62009155]
  [0.97780974 0.77977778 0.42719729]]

 [[0.38995664 0.18811921 0.15066886]
  [0.82393036 0.63199316 0.22398636]
  [0.09558114 0.33285623 0.56451095]]]


# Работа с файлами и каталогами  

## Путь к интерпретатору

In [ ]:
import sys
print(sys.executable)

c:\Users\wernadsky\miniconda3\envs\tf\python.exe


## Путь к рабочему каталогу

In [ ]:
import os
work_dir = os.path.abspath("")
print(work_dir)

c:\Users\wernadsky\Documents\GitHub


In [ ]:
import os
work_dir = os.getcwd()           # возвращает путь к рабочему каталогу
print(work_dir)

c:\Users\wernadsky\Documents\GitHub


## Путь к исполняемому файлу

### Для файлов `*.ipynb`

In [ ]:
import os
file_path = globals()['_dh'][0]     # путь к исполняемому файлу
print(str(file_path))

c:\Users\wernadsky\Documents\GitHub\Misc_Private


### Для файлов `*.py`

In [ ]:
# from os.path import abspath, dirname
# path = abspath(__file__)      # возвращает полное имя текущего файла
# location = dirname(path)      # извлекает путь из полного имени файла

> Пути к исполняемому файлу и рабочий каталог могут не совпадать:

In [ ]:
import os
os.chdir("..")
file_path = str(globals()['_dh'][0])    # путь к исполняемому файлу
work_dir = os.getcwd()                  # путь к рабочему каталогу
print(f"{file_path = }\n{work_dir =  }")

file_path = 'c:\\Users\\wernadsky\\Documents\\GitHub\\Misc_Private'
work_dir =  'c:\\Users\\wernadsky\\Documents\\GitHub'


По умолчанию текущим рабочим каталогом будет каталог, из которого запускается файл в коммандной сторке, а не каталог, в котором расположен исполняемый файл.

Кроме того, пути поиска файлов не имеют никакого отношения к путям поиска модулей.

## Прочие функции


`os.mkdir('folder')` создает новую директорию

`os.makedirs('another1/another2/another3')` – сделать несколько вложенных папок.
`os.rename("text.txt", "renamed-text.txt")` – переименование файла или папки.

Переместить (с заменой) файл в другой каталог (переименовать полный путь):
`os.replace("renamed-text.txt", "folder/renamed-text.txt")`.

`os.path.isdir('folder')` возвращает `True`, если каталог `folder` существует.

`os.path.exists()` возвращает `True`, если файл с заданным именем существует.

`os.path.basename()` отбрасывает путь и оставляет тольк имя файла. Например, `'foo/bar'` превратится в `'bar'`, а `'foo/bar/'` превратится в `''`.

## Чтение файла и запись

In [ ]:
# Чтение
with open('Python\\file', 'r') as file:
    file.read()         # получить содержимое файла
    file.readline()     # построчное стение
    file.readlines()    # получить список строк
    for line in file:   # перебор строк файла
        print(line)

# Запись
with open('Python\\file', 'w') as file:
    file.write('some text')            # запись в файл
    file.writelines(['some', 'text'])  # запись списка строк в файл

Переменная `file` является объектому класса _io.TextIOWrapper. С другими методами этого класса можно ознакомиться <a href="https://www.w3schools.com/python/python_ref_file.asp">здесь</a>

## Скачивание модуля из репозитория

`os.path.urlretrieve` копирует объект на диск. Первый аргумент -
**url** объекта. Если второй аргумент не задан, то объект будет сохранен во временных файлах. Можно задать имя файла, и тогда объект будет сохранен в рабочей директории с указанным именем. Функция возвращает кортеж `(filename, headers)` – имя файла и заголовки запроса.

In [ ]:
from os.path import basename, exists

def download(url):
    filename = basename(url)
    if not exists(filename):
        from urllib.request import urlretrieve
        local_filename, headers = urlretrieve(url, filename)
        print('Downloaded ' + local_filename)
    else:
        print('file ' + filename + ' already exists')

url = "https://raw.githubusercontent.com/ordevoir/Miscellaneous/master/tools.py"

download(url)

import tools

tools.LinkedList()

file tools.py already exists


[]

# Области видимости  

Часто глобальные переменные используются в качестве флагов логических переменных, которые могут играть роль режимов или настроек программы.



In [5]:
count = True        # глобальная переменная
def example():
    if count:       # использование переменной
        print('variable count is True!')

example()

variable count is True!



## Правило **LEGB**

Когда производится обращение к переменной, интерпертатор ищет ее в следующем порядке:
- в локальной области видимости самой функции (**Local** Scope)
- в локальной области видимости объемлющей функции (**Enclosing** Scope)
- в глобальной области видимости модуля (**Global** Scope)
- во встроенной области видимости (**Built-in** Scope)

Последная область относится к встроенному модулю с именем `builtins` стандартной библиотеки. Имена этого модуля представляют собой встроенные функции, такие как `print()`, `range()`, `len()`, `list()`, `object()` и т.д. Подробнее [здесь](https://docs.python.org/3/library/functions.html).


## `global` и `nonlocal`

Для изменение значения неизменяемой глобальной переменной внутри функции, или присвоения ей нового значения, необходимо в теле функции объявить имена переменных глобальными при помощи оператора `global`.

В коде ниже содержимое глобальных перменных `a` и `b` изменится внутри функции `example()`. Перменная `c` не будет изменена: инструкция `c = 10` создаст локальную переменнус `c`.

In [6]:
a, b, c = 1, 2, 3   # глобальная переменная
def example1():
    global a, b     # без этой строки не сработает
    a += 1          # изменение глобальной переменной
    b = 5           # присвоение нового значения глобальной переменной
    c = 10          # создание локальной переменной внутри функции

example1()
print(f"{a = }, {b = }, {c = }")

a = 2, b = 5, c = 3


Если глобальной переменной указанной в `global` не существует, она будет создана, однако при этом необходимо произвести инициализацию значения.

In [9]:
def example2():
    global x    # объявление глобальной переменной x
    x = 15      # инициализация глобальной переменной

def f():
    global x    # использовать глобальную переменную x
    x += 15     # изменение глобальной переменно внутри другой функции

In [11]:
example2()      # создание и инициализация глобальной переменной x внутри функции
print(x)

f()             # изменение глобальной переменно внутри другой функции
print(x)

x += 10         # изменение глобальной переменной за пределами функции
print(x)

15
30
40


> Оператор `nonlocal`, в отличие от `global` сделат переменную видимой не в глобальной области, а лишь в локальной области видимости объемлющей функции (Enclosing scope).

## `globals()` и `locals()`

Функция `globals()` возвращает словарь, содержащий глобальные переменные.

Функция `locals()` возвращает словарь, содержащий имена в локальной области видимости, внутри которой вызывается функция. Непосретственно список с именами локальных переменных возвращает функция `dir()`.

> Словарь, возвращаемый функцией `locals()` при вызове из глобальной области видимости, будет совпадать со словарем, возвращаемым функцией `globals()`.

In [42]:
def f(x):
    a = 2
    print(f"Function's local variables: {locals().keys()}")
    print(f"Function's local variables: {dir()}")
    print(f"Global variables: {globals().keys()}")

c = 3

f(c)

locals() is globals()

Function's local variables: dict_keys(['x', 'a'])
Function's local variables: ['a', 'x']
Global variables: dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', '_', '__', '___', '_i', '_ii', '_iii', '_i1', '_1', '_i2', '_2', '_i3', '_3', '_i4', '_4', '_i5', '_5', '_i6', '_6', '_i7', '_i8', '_i9', 'f', '_9', '_i10', '_10', '_i11', 'c', '_i12', '_12', '_i13', '_13', '_i14', '_14', '_i15', '_15', '_i16', '_16', '_i17', '_17', '_i18', '_18', '_i19', '_19', '_i20', '_20', '_i21', '_21', '_i22', '_22', '_i23', '_i24', '_24', '_i25', '_25', '_i26', '_26', '_i27', '_27', '_i28', '_i29', '_i30', 'L', '_i31', '_31', '_i32', '_i33', '_i34', 'Rectangle', 's2', 's3', '_i35', '_i36', '_i37', '_i38', '_i39', '_39', '_i40', '_i41', '_41', '_i42'])


True

## Замыкания (closure)

Замыкание – это особый вид функции. Она определена в теле другой функции и создаётся каждый раз во время её выполнения. Синтаксически это выглядит как функция, находящаяся целиком в теле другой функции. При этом вложенная внутренняя функция содержит ссылки на локальные переменные внешней функции (для внутренней функции это область видимости Enclosing Scope). Каждый раз при выполнении внешней функции происходит создание нового экземпляра внутренней функции, с новыми ссылками на переменные внешней функции. Поэтому замыкания можно определить как функции с расширенной областью видииости, которая охватывает все неглобальные переменные, на которые есть ссылки в теле функции, хотя они в нем не определены.


Ссылки на переменные внешней функции действительны внутри вложенной функции до тех пор, пока работает вложенная функция, даже если внешняя функция закончила работу, и переменные вышли из области видимости. <br>
Замыкание связывает код функции с её лексическим окружением (местом, в котором она определена в коде). Лексические переменные замыкания отличаются от глобальных переменных тем, что они не занимают глобальное пространство имён. От переменных в объектах они отличаются тем, что привязаны к функциям, а не объектам.

In [48]:
def f(a):
    b = 2
    def g(c=10):
        """ Функция - замыкание """
        print(a*b, b**c)
    return g

h = f(3)
h(5)

6 32


![](images/closure.jpg)

В данном примере в теле внешней функции `f` определена внутренняя функция `g`, которая для своей работы ссылается на переменные `a` и `b` области видимости Enclosing Scope - локальная область видимости внешней функции. При вызове функции ее локальные переменные существуют только в процессе выполнения функции, после чего их убирает сборщик мусора. Интуитивно кажется, что после выполнения функции `f` переменные `a` и `b` должны были бы уничтожиться. Однако, внешняя функции возвращает внутреннюю фунцию `g`, которая сохраняется в перменной `h`, в результате чего она появляется в глобальной области видимости (как и функция `f`). Так как `h` ссылается на функцию `g`, определенную в ходе выполнения функции `f`, а функция `g` в свою очередь ссылается на локальные переменные фунции `f`, то после выполнения фунции `f` объекты, на которые ссылались соответствующие локальные переменные не уничтожаются, так как на них продолжает ссылаться функция `g`.

Объекты замыкания содержатся в поле `__closure__` объекта функции, который представляет собой кортеж объектов класса `cell`. Для того, чтобы получть доступ непосредственно к объекту замыкания, нужно обратиться к полю `cell_contents` соответствующего объекта класса `cell`:

In [58]:
print(type(h.__closure__), type(h.__closure__[0]))
print(h.__closure__[0].cell_contents, h.__closure__[1].cell_contents)

<class 'tuple'> <class 'cell'>
3 2


`a` и `b` – локальные переменные функции `f`, так как их инициализация происходит в теле функции `f`. Внутри `h` переменные `a` и `b` являются свободными, т.е. переменные не связаны с ее локальной областью видимости. 

Инспекция возвращенного объекта `h` показывает, что Python хранит имена локальных и свободных переменных в атрибуте `__code__` (объект класса `code`), который представляет собой откомпилированное тело функции. Каждому элементу кортежа `h.__closure__` соответствует имя в `h.__code__.co_freevars`, в котором содержатся имена свободных переменных. В `h.__code__.co_namevars` содержатся имена локальных переменных.

In [53]:
print(type(h.__code__))
print(h.__code__.co_varnames, h.__code__.co_freevars)

<class 'code'>
('c',) ('a', 'b')


Следующий пример. Реализуем счетчик как фунцию-замыкание:

In [60]:
def make_counter(count=0):
    def counter():
        # сделаем count нелокальным, чтобы можно было его изменять
        nonlocal count
        count += 1
        return count
    return counter

c = make_counter()

In [69]:
c()     # каждый вызов увеличивает значение count

9

In [1]:
# в программах, которые будут импортированы как модули, часто используется:
if __name__ == '__main__':
    print('code...')

# где __name__ — это встроенная переменная, которая настраивается при запуске
# программы. Если программа работает как скрипт, __name__ имеет значение
# '__main__'; в этом случае тестовый код выполняется. В противном случае,
# если модуль импортируется, тестовый код пропускается.

NameError: name 'mean' is not defined